### ISSUE TITLE
Symbol’s function definition is void: replace-buffer-contents

### ISSUE THREAD

**Issue by backwardspy** [proofit404/blacken#22]
#19 introduced a new way to replace the whole buffer. Unfortunately, this function only exists in Emacs 26 and onwards. As a result, `blacken` now produces this error message on Emacs versions below 26:

```Symbol’s function definition is void: replace-buffer-contents```

In my case, I am using the latest Ubuntu LTS (18.04.2) which provides [GNU Emacs 25.2.2](https://packages.ubuntu.com/bionic/emacs).

Is there any way to fallback to the old behaviour (or an alternative method) for older Emacs versions?

Thanks.

**Comment by proofit404** [comment]
I reverted #19
