### ISSUE TITLE
How to change blacken-line-length?

### ISSUE THREAD

**Issue by fhbartlett** [proofit404/blacken#24]
My blacken-line-length is stuck at 79, even though C-h v blacken-line-length returns 100.

I even attempted
```
(defcustom blacken-executable "black --line-length 100"
  "Name of the executable to run."
  :type 'string)
```
but that also had no effect.

It looks like black overrides any changes from blacken.el

**Comment by CeleritasCelery** [comment]
I am not able to reproduce this. When I set `blacken-line-length` to 100 it works. What is your output of `M-: (blacken-call-args)`? Are you sure that you don't have any project specific settings?
