### ISSUE TITLE
Error message I'm having trouble to understand

### ISSUE THREAD

**Issue by jacob414** [proofit404/blacken#3]
Hello!

Thanks for implementing this, I'm very keen on integrating black with my Emacs!

I'm trying to get it running and I'm getting an error I can't seem to understand though:

I have configured my `blacken-executable` to a valid path. The executable works when I execute it on a Python module from the command line. I have also added a correct `LC_ALL` as an environment variable in Emacs. After turning on `blacken-mode`, I get the message "Black failed, see *blacken-error* buffer for details".

But when I look in the buffer *blacken-error*, all I see is the line "reformatted -".

Do you have any pointer on what I'm doing wrong?

**Comment by proofit404** [comment]
Reformatted looks like a message from the previous run. Do you have e reproducible example?

**Comment by andersk** [comment]
Here’s an example.

```python
print 'hello'
```

(`black` refuses to reformat Python 2–only syntax without `--fast`. But it does print an error message, and `blacken-buffer` fails to propagate it to the `*blacken-error*` buffer.)

**Comment by CeleritasCelery** [comment]
black does not support python 2 syntax without the `--fast` option. You can enable this with `(setq blacken-fast-unsafe t)`.

**Comment by andersk** [comment]
Please reread my comment. I know that `black` doesn’t support Python 2 syntax without the `--fast` option. When run standalone, it prints an error message to that effect. But the bug here is that this Emacs package **fails to propagate this error message** to a place where the user can see it. The `*blacken-error*` buffer is empty.

**Comment by CeleritasCelery** [comment]
Using your example I see the correct error message in `*blacken-error*`.

```
error: cannot format -: cannot use --safe with this file; failed to parse source file with Python 3.6's builtin AST. Re-run with --fast or stop using deprecated Python 2 syntax. AST error message: Missing parentheses in call to 'print'. Did you mean print(t "hello")? (<unknown>, line 2)
All done! 💥 💔 💥
1 file failed to reformat.
```
are you using the latest version of black and blacken?

**Comment by jacob414** [comment]
Haven't checked for a while, will try when I get a chance.

**Comment by andersk** [comment]
I have Black 19.3b0 from PyPI, blacken 20190521.841 from MELPA, and Python 3.7.4-4 and Emacs 26.1+1-4ubuntu1 from Ubuntu 19.10. Same results after upgrading to blacken-20190917.535.

**Comment by andersk** [comment]
Oh! I see what has happened. The `*blacken-error*` buffer is not empty, but all its contents have been scrolled off-screen. And if I scroll them back on-screen and rerun blacken, they’re scrolled back off-screen again.
