### ISSUE TITLE
Conflict with super-save-mode

### ISSUE THREAD

**Issue by alienbogart** [proofit404/blacken#31]
When used in conjunct with https://github.com/bbatsov/super-save, Blacken fails to keep the cursor at the same position (does not save excursion), and it ends up going to the top of the file.

This does not occur with super-save in any other mode, nor if I save the python file manually.

**Comment by alienbogart** [comment]
It turns out the issue was of my own making - I altered a vital function on super-save-mode. Sorry for the time wasted.

**Comment by alienbogart** [comment]
Nope. I was wrong.

**Comment by CeleritasCelery** [comment]
Closed in favor of #33
