### ISSUE TITLE
*blacken-error* appears empty on error if scroll-conservatively is nonzero

### ISSUE THREAD

**Issue by andersk** [proofit404/blacken#34]
If you customize `scroll-conservatively` to a nonzero value, and try to use `blacken-buffer` on a Python file with a syntax error, such as

```python
print("oops')
```

the resulting error message appears empty. What’s actually happened is that the error in the `*blacken-error*` buffer has been scrolled off-screen:

![screenshot](https://user-images.githubusercontent.com/26471/69216260-a3038f80-0b20-11ea-9d9f-7bb4a2b543e3.png)

If you scroll the message on-screen and re-run `blacken-buffer`, the message is scrolled back off-screen.

Expected result, as occurs with `scroll-conservatively` left at its default of `0`:

![screenshot](https://user-images.githubusercontent.com/26471/69216371-eeb63900-0b20-11ea-99d6-5bc0ad860cb6.png)

I’m using Emacs 26.3 on Ubuntu 20.04.

Split off from #3, but properly diagnosed this time, I hope.

**Comment by CeleritasCelery** [comment]
Thanks for diagnosing this. Please test.

**Comment by andersk** [comment]
That seems to have worked, thanks.
