### ISSUE TITLE
Feature-request: Don't open errors buffer when the error is "can't find black"

### ISSUE THREAD

**Issue by shaneikennedy** [proofit404/blacken#36]
👋 First off, thanks for this package!

I like using black to the point where I want to use it in any project I'm working on and I can just sync `python-mode` and `blacken-mode`, so the "can't find black" error is pretty much not an issue in these cases. The odd case is when I'm working on a one-off python script and every time I save it spawns the black-errors buffer and it's quite annoying.

Interested in  your thoughts about moving this one particular error to the `*messages*` buffer because it's much less intrusive, and still makes contextual sense since the error isn't really an error about black formatting, but rather a process error.

I'm sure there are work-arounds that I could try in my emacs config but thought this was worth bringing up and thought I'd ask here before I consider trying it out and opening a PR.

**Comment by CeleritasCelery** [comment]
Does setting the option `blacken-only-if-project-is-blackened` solve your issue? that will check if a project has `pyproject.toml` with black enabled. If not it will not enable the mode.

**Comment by shaneikennedy** [comment]
Ah it probably does, I haven't already set this because one certain project I work on hasn't adopted black in the codebase but I still like to use it from time to time. This is getting too specific for my use case, I'll close the issue. 

Thanks for getting back to me!
