### ISSUE TITLE
When trying to close blacken-error it freezes my Emacs

### ISSUE THREAD

**Issue by chookity-pokk** [proofit404/blacken#39]
I am on Windows 10 running this on Emacs 26.2 and every time I try to kill the blacken-error buffer it freezes Emacs.

**Comment by jontsai** [comment]
Might this issue be related to #52, which was affecting Emacs v26? I also use this package on Emacs v27, 28.

A proposed fix is in #53.

**Comment by dakra** [comment]
Thanks.

I'll close this but please do reopen if there's still something wrong.
