### ISSUE TITLE
How does this scale over tramp?

### ISSUE THREAD

**Issue by justinjk007** [proofit404/blacken#4]
Do I need to have black on the server I am sshing into to blacken any-files in there ? or can I use my on local black ?

**Comment by storax** [comment]
This sends your buffer contents to black via stdin. So you don't need it on the other end. Should be fine to use via tramp.

**Comment by proofit404** [comment]
Hi, I'm using it just fine with tramp buffers and black installed locally.

**Comment by jsigman** [comment]
Am I correct to notice that it works on tramp, but does not run the black executable on the server? I am having trouble getting it to respect `pyproject.toml` that is on the server side but which should apply to my tramp buffer
