### ISSUE TITLE
Annoying when using two windows on the same buffer

### ISSUE THREAD

**Issue by leotrs** [proofit404/blacken#49]
I usually have two windows showing the same buffer, where the point is at different positions within the buffer. When working on one and running blacken, the other window's point is reset all the way to the top of the file. This makes blacken pretty much unusable for me.

**Comment by leotrs** [comment]
Awesome thanks!!!

**Comment by newt0311** [comment]
I had the same problem as you: working on a complex module that I needed three (!) separate windows to display on... This fix increased my productivity by a non-trivial percentage.
