### ISSUE TITLE
Error: Invalid value for "src": Path "-" does not exist.

### ISSUE THREAD

**Issue by sidmitra** [proofit404/blacken#8]
Added the following to me emacs config
`(add-hook 'python-mode-hook 'blacken-mode)`

and when running `blacken-buffer` on a python buffer i get the following in the error buffer.

```
Usage: black [OPTIONS] [SRC]...

Error: Invalid value for "src": Path "-" does not exist.
```

**Comment by sidmitra** [comment]
For some reason this error went away. Even though nothing in my config changed. Probably has something to do with paths and pipenv(and where black is installed). Closing this.

**Comment by liushen595** [comment]
I knew it.Your path can't exist space,I change it to '_',and the problem solved.

**Comment by liushen595** [comment]
I knew it.Your path can't exist blank space,I change it to '_',and the problem solved.
