### ISSUE TITLE
Custom arguments

### ISSUE THREAD

**Issue by lgvaz** [proofit404/blacken#9]
First of all, I'm a emacs noob.

I want to execute black with custom arguments, I see there's a function for doing that [here](https://github.com/proofit404/blacken/blob/master/blacken.el#L79) but I don't know how to actually use it.

For instance, I want to run black with the "-S" flag.

I don't think this changes anything, but I'm using spacemacs.

**Comment by proofit404** [comment]
Hi,

Fixed in the 1c3ad7211d1e9936203d63f9e2206e1978d7be50

To use it add following lines to your config:

```lisp
(setq blacken-skip-string-normalization t)
```

Regards, Artem.
